# Training params
batch_size: 128
lr: 0.0002
beta_start: 0.0001
beta_end: 0.02
num_timesteps: 1000
num_epochs: 1000
gpu_ids:
  - 0
  - 1
  - 2
log_dir: runs
ckpt_dir: checkpoints
dataset: cifar10
interval: 50
# U-Net backbone settings
unet:
  in_channels: 3
  out_channels: 3
  basic_width: 64
  ch_mult:
    - 1
    - 2
    - 4
    - 8
  num_blocks: 2
  num_mid_blocks: 2
  drop_prob: 0.1
  attention:
    - False
    - True
    - False
    - False
  resample_with_conv: True
